// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPZTIcJWKoqwW1-x9A8t68PtJx51gc3Ao',
    appId: '1:625606690178:web:bac8b8d16ce78b8c313b9b',
    messagingSenderId: '625606690178',
    projectId: 'wallmazing-a0ea0',
    authDomain: 'wallmazing-a0ea0.firebaseapp.com',
    storageBucket: 'wallmazing-a0ea0.appspot.com',
    measurementId: 'G-TWTXH42RCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU1kuzhUXz6G-o9kphniETA4NCQdCL5io',
    appId: '1:625606690178:android:de78f88fcec01df4313b9b',
    messagingSenderId: '625606690178',
    projectId: 'wallmazing-a0ea0',
    storageBucket: 'wallmazing-a0ea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADAWAwqU4FWy55ntMSVenIv6C3AnuCNkg',
    appId: '1:625606690178:ios:e6db98004cf6faf2313b9b',
    messagingSenderId: '625606690178',
    projectId: 'wallmazing-a0ea0',
    storageBucket: 'wallmazing-a0ea0.appspot.com',
    iosClientId: '625606690178-9ncte70m4l03ak9kffm4529t7nku7k9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpappers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADAWAwqU4FWy55ntMSVenIv6C3AnuCNkg',
    appId: '1:625606690178:ios:e6db98004cf6faf2313b9b',
    messagingSenderId: '625606690178',
    projectId: 'wallmazing-a0ea0',
    storageBucket: 'wallmazing-a0ea0.appspot.com',
    iosClientId: '625606690178-9ncte70m4l03ak9kffm4529t7nku7k9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpappers',
  );
}
